### ISSUE TITLE
Video for course project

### ISSUE THREAD

**Issue by vladdimakov** [cvlabmiet/cvclasses19#22]
[TestVideo.mp4](https://drive.google.com/open?id=1LANvK7haPL8cYQ3V0mpiM8n8NVLFDhYU)

**Comment by DVukalov** [comment]
nice

**Comment by vladdimakov** [comment]
[TestVideo.mp4.txt](https://github.com/cvlabmiet/cvclasses18/files/2580977/TestVideo.mp4.txt)

**Comment by DVukalov** [comment]
[TestVideo.mp4.txt](https://github.com/cvlabmiet/cvclasses18/files/2580979/TestVideo.mp4.txt)

**Comment by KonochkinKN** [comment]
[TestVideo.mp4.txt](https://github.com/cvlabmiet/cvclasses18/files/2580980/TestVideo.mp4.txt)

**Comment by DVukalov** [comment]
kek

**Comment by dkalina-vm21** [comment]
[TestVideo.mp4.txt](https://github.com/cvlabmiet/cvclasses18/files/2580981/TestVideo.mp4.txt)

**Comment by DVukalov** [comment]
Vlad is love

**Comment by DVukalov** [comment]
![ikqxt78wykg](https://user-images.githubusercontent.com/18100235/48487295-d84f1080-e82e-11e8-8fd0-26675f002d6b.jpg)
Vlad is love

**Comment by DVukalov** [comment]
![22411034](https://user-images.githubusercontent.com/18100235/48487354-07658200-e82f-11e8-80cf-a04f528785e2.jpg)

**Comment by DVukalov** [comment]
[https://memepedia.ru/wp-content/uploads/2018/06/drizi-i-kezi.jpg](url)

**Comment by DVukalov** [comment]
[TestVideo.mp4.txt](https://github.com/cvlabmiet/cvclasses18/files/2591841/TestVideo.mp4.txt)

**Comment by antonsh26** [comment]
[TestVideo.mp4.txt](https://github.com/cvlabmiet/cvclasses18/files/2591947/TestVideo.mp4.txt)

**Comment by egorovp** [comment]
[TestVideo.mp4.txt](https://github.com/cvlabmiet/cvclasses18/files/2613682/TestVideo.mp4.txt)

**Comment by Pol22** [comment]
[TestVideo.mp4.txt](https://github.com/cvlabmiet/cvclasses18/files/2644013/TestVideo.mp4.txt)
